### ISSUE TITLE
verbose issue

### ISSUE THREAD

**Issue by cuchorapido** [rschwabco/babyagi-langchain-ts#1]
root@fe61f4ddfbe2:/opt/new/babyagi-langchain-ts# npm run local:watch

> node-typescript-project-template@1.0.0 local:watch
> nodemon src -e ts,json --exec 'npm run local'

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `npm run local src`

```
> node-typescript-project-template@1.0.0 local
> ts-node src "src"

/opt/new/babyagi-langchain-ts/node_modules/langchain/dist/chains/base.cjs:30
        this.verbose = verbose ?? (callbackManager ? true : getVerbosity());
                                ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .js] (/opt/new/babyagi-langchain-ts/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/new/babyagi-langchain-ts/node_modules/langchain/dist/chains/index.cjs:4:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR! code 1
npm ERR! path /opt/new/babyagi-langchain-ts
npm ERR! command failed
npm ERR! command sh -c ts-node src "src"

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-04-12T21_02_15_233Z-debug.log
[nodemon] app crashed - waiting for file changes before starting...
^C
root@fe61f4ddfbe2:/opt/new/babyagi-langchain-ts#
```

error logs:

```
root@fe61f4ddfbe2:/opt/new/babyagi-langchain-ts# cat /root/.npm/_logs/2023-04-12T21_02_15_233Z-debug.log
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'local', 'src' ]
1 info using npm@7.5.2
2 info using node@v12.22.12
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/share/nodejs/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/opt/new/babyagi-langchain-ts/.npmrc Completed in 1ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:/root/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 8ms
19 verbose npm-session 5f7a23114ec1518e
20 timing npm:load Completed in 16ms
21 timing command:run-script Completed in 6510ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:314:20)
22 verbose stack     at maybeClose (internal/child_process.js:1022:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
23 verbose pkgid node-typescript-project-template@1.0.0
24 verbose cwd /opt/new/babyagi-langchain-ts
25 verbose Linux 5.10.102.1-microsoft-standard-WSL2
26 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "local" "src"
27 verbose node v12.22.12
28 verbose npm  v7.5.2
29 error code 1
30 error path /opt/new/babyagi-langchain-ts
31 error command failed
32 error command sh -c ts-node src "src"
33 verbose exit 1
root@fe61f4ddfbe2:/opt/new/babyagi-langchain-ts#
```

**Comment by rschwabco** [comment]
Seems to be an error with the installed version of LangChain. I'm a bit confused by this though, and can't repro. Can you please provide more details? Node version etc.
